### PR TITLE
Update tvdb4.mapping

### PR DESCRIPTION
**Pull request by sven-7**
Adding Dragon Ball Kai as test.

### CODE REVIEW

**Comment by EndOfLine369** [comment]
@sven-7 
In review of the episodes after using it in Plex, I actually believe something is wrong in your breakdown.
```
1|001|016|Saiyan Saga
2|017|030|Namek Saga
3|031|054|Freiza Saga
4|055|067|Android Saga
5|068|098|Cell Saga
```
In review of the episodes I see in Plex, it looks like it should probably be:
```
1|001|016|Saiyan Saga
2|017|028|Namek Saga
3|029|036|Ginyu Saga
4|037|054|Frieza Saga
5|055|067|Androids Saga
6|068|082|Cell Saga
7|083|098|Cell Games Saga
```
Thoughts?

**Comment by EndOfLine369** [comment]
Mainly clarification of 'Namek/Ginyu/Frieza' and separation of 'Cell Saga'.

**Comment by EndOfLine369** [comment]
http://dragonball.wikia.com/wiki/List_of_sagas
```
Episodes (Kai) 01-16 - Vegeta Saga
Episodes (Kai) 17-31 - Namek Saga
Episodes (Kai) 32-35 - Captain Ginyu Saga
Episodes (Kai) 36-54 - Frieza Saga
Episodes (Kai) 55-58 - Trunks Saga
Episodes (Kai) 59-67 - Androids Saga
Episodes (Kai) 68-75 - Imperfect Cell Saga
Episodes (Kai) 76-82 - Perfect Cell Saga
Episodes (Kai) 83-98 - Cell Games Saga
```

**Comment by ZeroQI** [comment]
Hummm... the story should be split into archs, not the number of eps, but 15 arcs listing is ridiculous in my opinion. The "too broad one" is actually nice, the 7 arc split one is probably my favorite, especially as kai is a re-edit and some of this fight arcs might be wished to be skipped, like the "Ginyu Force" (dairy brigade) but should this matter in the decision-making process ? I am hoping for over 9000 points with this post :p

**Comment by EndOfLine369** [comment]
The 4 season arc listing might be the best and fit the spirit of tvdb4. Even though the last season has 61 episodes. This will only be the first of many that we might have to deal with in diff listings of episode groupings. Also note that the 7 season I listed is only going down from 9 in the larger listing (001--098) so there are still more listings pending in my list in the first comment. Probably more weight to the 4 season core arc listings.

**Comment by EndOfLine369** [comment]
@ZeroQI If you agree on the 4 arc core seasons, i'll update the file.

**Comment by EndOfLine369** [comment]
The only other listings is on Wikipedia but the start/stop ep numbers are mostly crap.
https://en.wikipedia.org/wiki/List_of_Dragon_Ball_Z_Kai_episodes
But the seasons are actually more reasonable and close to the Wikia arc listings.
```
Episodes (Kai) 001-016 - Season 1: Saiyan Saga
Episodes (Kai) 017-054 - Season 2: Frieza Saga
Episodes (Kai) 055-067 - Season 3: Androids Saga
Episodes (Kai) 068-098 - Season 4: Cell Saga
Episodes (Kai) 099-133 - Season 5: Majin Buu Saga
Episodes (Kai) 134-159 - Season 6: Evil Buu Saga
```

**Comment by sven-7** [comment]
You're right.  I'm all on board with 4 season.  Someone pointed that out to me yesterday and thinking about it now, logically it makes sense to wrap Namek/Ginyu/Freiza into Freiza.  I had already wrapped Cell/Cell Games into Cell.  I'm all good with this.

This does bring up an interesting point.  What do we do when there are disagreements on what goes on the list?  Granted, at the end of the day, if someone wanted to have 5 seasons, tvdb4 still allows them to do that.

**Comment by ZeroQI** [comment]
@EndOfLine369  Yep 4 seasons looks good and make most sense, they are proper sagas.
Too many episodes (100+) in a season cause problems on some phone/tablets to scroll down...
Your screenshot show studio logo which look good, but more especially show custom posters for arcs, that look super cool, stunning, but we cannot possibly upload them to thetvdb as they don't match their notion of seasons....

Is there any way to have these posters in a folder in a git folder (tvdbid#-season#.jpg)?

**Comment by sven-7** [comment]
I think some way we can have images pulled down would be fantastic.  Does anyone have any thoughts on that?  I'm not sure of any free repository we could use off the top of my head.

**Comment by EndOfLine369** [comment]
We should be able to store in ASS Git, but I don't think we should have HAMA pull them down unless there is a way for HAMA to know that the seasons are based on the Git xml file.
Did a test image upload: [tvdb4/tvdb4-88031/tvdb4-88031-season4.jpg](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4/tvdb4-88031/tvdb4-88031-season4.jpg)
Is this a good folder format? "tvdb4/tvdb4-#/tvdb4-#-season#.jpg"
Each series should really have its own folder in planning for a lot or more series/seasons for better grouping/visibility. Mainly asking on folder/filename name format.

**Comment by sven-7** [comment]
We probably don't need the tvdb4 in there that many times. Maybe:

tvdb4/tvdb4-88031/88031-04.jpg

or

tvdb4/tvdb4-88031 (Dragon Ball Kai)/88031-04.jpg

**Comment by EndOfLine369** [comment]
Hmmmm....On further thought, maybe we don't want to store these images at all. I could see people complain about image rights. We could just store the URLs to the images. And still need a way for HAMA to know when the xml is used for seasons.

As xml, we can easily just add in a separate entry to not interfere with the other entries as we are defining for anime tags `"/tvdb4entries/anime[@tvdbid='%s']"`.
EX:
```xml
  <anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|Saiyan Saga
    02|017|054|Frieza Saga
    03|055|067|Androids Saga
    04|068|098|Cell Saga
    05|099|133|Majin Buu Saga
    06|134|159|Evil Buu Saga
  </anime>
  <posters tvdbid="88031" name="Dragon Ball Kai">
    01|[URL]
    02|[URL]
    03|[URL]
    04|[URL]
    05|[URL]
    06|[URL]
  </posters>
```

**Comment by EndOfLine369** [comment]
Would not recommend separating into separate files and that could be an issue when reconciling file entries.

**Comment by sven-7** [comment]
I think the URL solution is a good compromise from a storage/rights perspective.  Could we design it either way so there can be more than one per season?  For example:

```
 <anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|Saiyan Saga
    02|017|054|Frieza Saga
    03|055|067|Androids Saga
    04|068|098|Cell Saga
    05|099|133|Majin Buu Saga
    06|134|159|Evil Buu Saga
  </anime>
  <posters tvdbid="88031" name="Dragon Ball Kai">
    01|[URL]
    01|[URL]
  </posters>
```

**Comment by EndOfLine369** [comment]
I don't see an issue with that to allow people different pictures available. But would probably need to make a rule for the file of only X images max per season. 2 per season?

**Comment by sven-7** [comment]
Seems fair to me.

**Comment by ZeroQI** [comment]
<anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|[URL]|Saiyan Saga
    02|017|054|[URL]|Frieza Saga
    03|055|067|[URL]|Androids Saga
    04|068|098|[URL]|Cell Saga
    05|099|133|[URL]|Majin Buu Saga
    06|134|159|[URL]|Evil Buu Saga
  </anime>
I thought you did the posters yourself...
If thetvdb have them yes a link will be great

Would not recommend separating into separate files and that could be an
issue when reconciling file entries.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ZeroQI/Absolute-Series-Scanner/pull/36#issuecomment-226621091>,
or mute the thread
<https://github.com/notifications/unsubscribe/AE7LZXwtvcaMPKHXw86IrXgnujP_V_Dnks5qMcHIgaJpZM4I29ig>
.

**Comment by EndOfLine369** [comment]
"Would not recommend separating into separate files and that could be an issue when reconciling file entries." I had already mentioned that or are you meaning separate entries in the file?

If we combined the 'anime' & 'poster' tags, we could not have more than one poster available for a season. I would prefer not all to be in one entry as the url will make the line exceedingly long and would think is best to keep the 'anime' entry same as the local 'tvdb4.mapping' file's content.

**Comment by ZeroQI** [comment]
The poster is done by the agent so technically no need for a single file having both but it's simpler...

We could have a variable number of arguments, the format stays compatible and allows local file to specify poster link too...

<anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|Saiyan Saga|[URL]|[URL]
    02|017|054|Frieza Saga|[URL]|[URL]|[URL]
    03|055|067|Androids Saga|[URL]
    04|068|098|Cell Saga|[URL]|[URL]
    05|099|133|Majin Buu Saga|[URL]|[URL]|[URL]
    06|134|159|Evil Buu Saga|[URL]|[URL]
  </anime>

The tvdb id would be unique so i don't think there will be issues reconciliating entries, like what we do with the xml mapping file from scudlee's... single file easier to maintain... 

tvdb4.posters.xml
 <posters tvdbid="88031" name="Dragon Ball Kai">
    01|[URL]
    01|[URL]
    02|[URL]
    02|[URL]
    03|[URL]
    04|[URL]
    05|[URL]
    06|[URL]
  </posters>

Opinions?

**Comment by EndOfLine369** [comment]
Lets move this into an enhancement ticket from this closed pull request.

**Pull request merged**
