### PR TITLE
Zero qi patch 2

### PR DESCRIPTION
**Pull request by ZeroQI**
code re-written for concision

### CODE REVIEW

**Comment by EndOfLine369** [comment]
Something looks wrong on the 'TVDB season mode' changes. Everything else looks ok. I'll review the 'TVDB season mode' changes more and test myself.

**Comment by EndOfLine369** [comment]
It is indeed broken. Will fix and provide.

**Comment by EndOfLine369** [comment]
ok, maybe not....
I think my brain might be dead from work.....

**Comment by EndOfLine369** [comment]
Ok, I corrected and updated my scanner with your updates plus the fix to the tvdb2/3 section. It won't even scan. Not sure what is wrong.

**Comment by EndOfLine369** [comment]
Looks like your 'import Stack'/'Stack.Scan' addition is causing the scanner to not run.

**Comment by EndOfLine369** [comment]
Any idea why that addition would cause this issue? Not logging.

```
2016-05-03 23:24:31 Place correct Plex token in X-Plex-Token.id file in logs folder or in PLEX_LIBRARY_URL variable to have a log per library - https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token
2016-05-03 23:26:08 Place correct Plex token in X-Plex-Token.id file in logs folder or in PLEX_LIBRARY_URL variable to have a log per library - https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token
```

**Comment by EndOfLine369** [comment]
Looks like its the import 'import Stack' as comment out of the scan did not fix but import did.

**Comment by EndOfLine369** [comment]
Committed my fix to this branch. It has run clean against my library with no issues seen other then the 'import Stack' issue. I did not remove that piece even though it broke the code until you comment on it.

**Comment by ZeroQI** [comment]
Library may now be imported implicitely
removed import stack and added test to not crash if the stack module isn't loaded, but logging it
Sorry about the algorythm mistake when butchering the code, but was very happy with how it shrinked. In the past years, i often redid the code so it was shorter and easier but sometimes brought new bugs in the process ;P

Hopefully it should be stable now

**Comment by EndOfLine369** [comment]
Errors out
```
Error in Python: Running scanner:
Traceback (most recent call last):
  File "/root/Library/Plex Media Server/Scanners/Series/Absolute Series Scanner test.py", line 389, in Scan
    Stack.Scan(path, files, mediaList, subdirs) if "Scan" in dir(Stack) else Log("Stack.Scan() doesn't exists")
NameError: global name 'Stack' is not defined
```

**Comment by EndOfLine369** [comment]
Correction committed.

```
2016-05-05 22:20:25 Place correct Plex token in X-Plex-Token.id file in logs folder or in PLEX_LIBRARY_URL variable to have a log per library - https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token
2016-05-05 22:20:25 Scanner call - root: '/share/Anime2/Running', path: 'Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890', dirs: '0', files: '9'
2016-05-05 22:20:25 =============================================================================================================================================================
2016-05-05 22:20:25 file: '/share/Anime2/Running/Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890/[HorribleSubs] Sousei no Onmyouji - 01 [720p].mkv.torrent', ext: 'torrent' not in video_ext
2016-05-05 22:20:25 file: '/share/Anime2/Running/Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890/[HorribleSubs] Sousei no Onmyouji - 02 [720p].mkv.torrent', ext: 'torrent' not in video_ext
2016-05-05 22:20:25 file: '/share/Anime2/Running/Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890/[HorribleSubs] Sousei no Onmyouji - 03 [720p].mkv.torrent', ext: 'torrent' not in video_ext
2016-05-05 22:20:25 file: '/share/Anime2/Running/Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890/[HorribleSubs] Sousei no Onmyouji - 04 [720p].mkv.torrent', ext: 'torrent' not in video_ext
2016-05-05 22:20:25 file: '/share/Anime2/Running/Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890/info.ao', ext: 'ao' not in video_ext
2016-05-05 22:20:25 "Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890" s0001e001 "[HorribleSubs] Sousei no Onmyouji - 01 [720p].mkv"
2016-05-05 22:20:25 "Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890" s0001e002 "[HorribleSubs] Sousei no Onmyouji - 02 [720p].mkv"
2016-05-05 22:20:25 "Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890" s0001e003 "[HorribleSubs] Sousei no Onmyouji - 03 [720p].mkv"
2016-05-05 22:20:25 "Twin Star Exorcists (Sousei no Onmyouji) -i -lj -sU -a11785 [anidb-11785] -n17890" s0001e004 "[HorribleSubs] Sousei no Onmyouji - 04 [720p].mkv"
2016-05-05 22:20:25 -------------------------------------------------------------------------------------------------------------------------------------------------------------
2016-05-05 22:20:25
2016-05-05 22:20:25 Stack.Scan() doesn't exists
```

**Comment by EndOfLine369** [comment]
Ok, I have no idea what is going on with my tests. reinstated the Stack import. I un-commetted the import and got logs this time..... /sigh

**Comment by EndOfLine369** [comment]
I think I know whats going on.

Without the 'import Stack', when I manually run the 'Plex Media Scanner' against a directory it will force a scan of the directory no matter if the files changed or not. 

With Stack is imported, it will only scan the directory if the folder has changes (thus the no output). Just like a standard rescan call from the Plex GUI for a library.

We will just keep the import in the published scanner. I'll just have to remember to always remove the import when I test scanner updates against my files and thus force all files to be re-scanned with the updated code. As it would be the only time I would need a forced scan.

**Comment by EndOfLine369** [comment]
I think we can probably pull this branch now of your testing/review agrees.

**Comment by ZeroQI** [comment]
I couldn't understand why it worked without it for the guy that reported it...
Make more sense now. Thanks for that. You really allow bith the scanner and agent to have functionnalities and fixes quicker, and i am thankfull for that

**Pull request merged**
