### PR TITLE
Multiple Updates

### PR DESCRIPTION
**Pull request by EndOfLine369**
Update 'clean_string' for dot num specials so it does not start with a season/special char 'S|s' (s2.03) or a version char 'v' (v1.2)
Update 'http://thetvdb.com' to 'https://thetvdb.com'
Add 'Movies' setting if only one file in the folder & contains '-m' in the folder name denoting a movie folder
Add 'Movies/Single EP Shows' setting if only one file in the folder & it has no numbers in it (as would otherwise force it to a 500+ special)
Add commented log statements for easier debugging when needed
Update string with '-' parsing to stop string reassignment as was causing issue with series that have '<word>-<number>' in their title (EX: 'Aika R-16' & '07-Ghost') and to just continue onto the next string. If it indeed included the episode number, it will have to be caught in the next regex parsing loop. 
Update specials match to include most special strings to break out for regex filename processing
Update to reduce the 'misc.count(ep)>=3' down to 'misc.count(ep)>=2'
Update to prefix parsing test of 'ep[len(prefix):].isdigit()' to 're.match("^\d+(\.\d+)?$", ep[len(prefix):])' so it can handle dot num specials (EX: 12.5)
Update to dot special parsing to be after exclusion testing of repeated entries (EX: required for 'Tokyo Magnitude 8.0')

### CODE REVIEW

**Comment by EndOfLine369** [comment]
@ZeroQI, please help and peer review/test :smiley:

**Comment by EndOfLine369** [comment]
If you would like me to break this out into multiple commits, I can do that.

**Comment by ZeroQI** [comment]
I loose track of which remaining issues there is, lookes at the code changes, and i don't see problems but i know when changing regex i got issues that took forever to fix without making something else act up so am wary of them
I didn't know there were that many issues to fix... Is there any improvement to think about ?

**Comment by EndOfLine369** [comment]
**Oh, also this fix**: (was in the commit but just missed to add it into the list)
Fix folder season check on 4digit string test `int(ep[0:1])==folder_season` to `int(ep[0:2])==folder_season)` as was incorrectly only using the first char only


**On this one**:
Update string with '-' parsing to stop string reassignment as was causing issue with series that have '-' in their title (EX: 'Aika R-16' & '07-Ghost') and to just continue onto the next string. If it indeed included the episode number, it will have to be caught in the next regex parsing loop. 
###############
I think I might have an idea to essentially reinstate this in the loop. basically, elif test that the string 'R-16|'07-Ghost' is not in the folder_show, then do the split. Else still continue.
Will need to hold on this commit.......

Please also note that I don't expect any issues in any of the committed changes as have been testing each change with a full rescan of every file in my library.

**Comment by EndOfLine369** [comment]
Initial type up:
```
      if '-' in ep and len(filter(None, ep.split('-',1)))==2:                                                                                                                     # If separator in string
        if re.match("^(ep?[ -]?)?(?P<ep>[0-9]{1,3})(-|ep?|-ep?)(?P<ep2>[0-9]{1,3})", ep, re.IGNORECASE):      ep="Skip"; break                                                    # if multi ep: make it non digit and exit so regex takes care of it
        elif path and misc.count(ep)==1 or ep not in clean_string(folder_show, True).split():
          ep = ep.split('-',1)[0] if ''.join(letter for letter in ep.split('-',1)[0] if letter.isdigit()) else ep.split('-',1)[1];                                                # otherwise all after separator becomes word#words.insert(words.index(word)+1, "-".join(ep.split("-",1)[1:])) #.insert(len(a), x) is equivalent to a.append(x). #???
        else:                                                                                                 continue
```

Will test....

**Comment by ZeroQI** [comment]
You are more thorough than me for testing, which is good.
Looks good and logical to me

**Comment by EndOfLine369** [comment]
Initial testing for looks ok. Will test against full library.
```
      if '-' in ep and len(filter(None, ep.split('-',1)))==2:                                                                                                                     # If separator in string
        if re.match("^(ep?[ -]?)?(?P<ep>[0-9]{1,3})(-|ep?|-ep?)(?P<ep2>[0-9]{1,3})", ep, re.IGNORECASE):      ep="Skip"; break                                                    # if multi ep: make it non digit and exit so regex takes care of it
        elif path and ( (misc.count(ep)==1 and len(files)>=2) or ep not in clean_string(folder_show, True).lower().split() ):
          Log("Splitting : ep = " + ep + " : misc.count = " + str(misc.count(ep)) + " : len(files) = " + str(len(files)) + " : clean_string(folder_show, True).split() = " + str(clean_string(folder_show, True).split()) )
          ep = ep.split('-',1)[0] if ''.join(letter for letter in ep.split('-',1)[0] if letter.isdigit()) else ep.split('-',1)[1];                                                # otherwise all after separator becomes word#words.insert(words.index(word)+1, "-".join(ep.split("-",1)[1:])) #.insert(len(a), x) is equivalent to a.append(x). #???
        else:                                                                                                 continue
```
Log:
```
2016-05-01 21:52:14 Scanner call - root: '/share/Anime2/t1', path: 'Durarara!!   -f -lj', dirs: '0', files: '1'
2016-05-01 21:52:14 =============================================================================================================================================================
2016-05-01 21:52:14 Splitting : ep = tvd-2 : misc.count = 1 : len(files) = 1 : clean_string(folder_show, True).split() = ['Durarara!!', '-f', '-lj']
2016-05-01 21:52:14 "Durarara!! -f -lj" s0001e002 "[AniDub]_Durarara!!_ TVD-2_[01]_[720p_x264_Aac]_[MVO].mp4" "01"
2016-05-01 21:52:14 -------------------------------------------------------------------------------------------------------------------------------------------------------------
2016-05-01 21:52:14
2016-05-01 21:52:14 Scanner call - root: '/share/Anime2/t1', path: '07-Ghost  -f -lj', dirs: '0', files: '1'
2016-05-01 21:52:14 =============================================================================================================================================================
2016-05-01 21:52:14 "07-Ghost -f -lj" s0001e008 "07-Ghost - 08 -  Does the Soul that was Devoured by the Wings, Dream of Its Beloved Child [DB].avi" "Does the Soul that was Devoured by the Wings, Dream of Its Beloved Child"
2016-05-01 21:52:14 -------------------------------------------------------------------------------------------------------------------------------------------------------------
2016-05-01 21:52:14
2016-05-01 21:52:15 Scanner call - root: '/share/Anime2/t1', path: 'Zoids Genesis  -f -lj', dirs: '0', files: '2'
2016-05-01 21:52:15 =============================================================================================================================================================
2016-05-01 21:52:15 Splitting : ep = genesis-31 : misc.count = 1 : len(files) = 2 : clean_string(folder_show, True).split() = ['Zoids', 'Genesis', '-f', '-lj']
2016-05-01 21:52:15 "Zoids Genesis -f -lj" s0001e031 "[T-N]Zoids_Genesis-31[9DCCACD3]CM.avi" "CM"
2016-05-01 21:52:15 Splitting : ep = genesis-47 : misc.count = 1 : len(files) = 2 : clean_string(folder_show, True).split() = ['Zoids', 'Genesis', '-f', '-lj']
2016-05-01 21:52:15 "Zoids Genesis -f -lj" s0001e047 "[T-N]Zoids_Genesis-47[C3E5C322]andCM.avi" "andCM"
2016-05-01 21:52:15 -------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by EndOfLine369** [comment]
Looks good on my series with issue that questioned this piece in the first place. Full library scan still ongoing though...
```
2016-05-01 22:13:19 Scanner call - root: '/share/Anime/Archived', path: 'AIKa R-16 - Virgin Mission -f -lj -s6 -e3 -a4852 [anidb-4852] -n7170', dirs: '1', files: '4'
2016-05-01 22:13:19 =============================================================================================================================================================
2016-05-01 22:13:19 "/share/Anime/Archived/AIKa R-16 - Virgin Mission -f -lj -s6 -e3 -a4852 [anidb-4852] -n7170/.@__thumb" match ignore_dirs_rx: ".@__thumb"
2016-05-01 22:13:19 file: '/share/Anime/Archived/AIKa R-16 - Virgin Mission -f -lj -s6 -e3 -a4852 [anidb-4852] -n7170/Aika R-16.torrent', ext: 'torrent' not in video_ext
2016-05-01 22:13:19 "AIKa R-16 - Virgin Mission -f -lj -s6 -e3 -a4852 [anidb-4852] -n7170" s0001e001 "[PFSub] AIKa R-16 Virgin Mission 01(704x396)[704c5d33].mkv" "(704X396)"
2016-05-01 22:13:19 "AIKa R-16 - Virgin Mission -f -lj -s6 -e3 -a4852 [anidb-4852] -n7170" s0001e002 "[PFSub] AIKa R-16 Virgin Mission 02v2 ( XVID)(640x360)[4158752A].mkv" "XVID) (640x360)"
2016-05-01 22:13:19 "AIKa R-16 - Virgin Mission -f -lj -s6 -e3 -a4852 [anidb-4852] -n7170" s0001e003 "[PFSub] AIKa R-16 Virgin Mission 03 ( XviD 768x432)[38608B71].mkv" "768X432)"
```

**Comment by EndOfLine369** [comment]
Testing passed. I'm actually going to close this pull request and put in another one that has multiple commits to break apart the updates to make it clear what is for what.

**Pull request closed without merging**
