### PR TITLE
Filter Out Anidb Version Numbers

### PR DESCRIPTION
**Pull request by magnumdoomguy**
Anidb release version numbers (ie., Yuu Yuu Hakusho - 034v2 - Percentage
of Victory, Macross Frontier - 04v2 - Miss Macross, etc.) were not being
identified correctly.  Added v2, v3, v4 to whack.

### CODE REVIEW

**Comment by ZeroQI** [comment]
Hi, while that work for you, this code should be in the regex as some series does use v1/2/3 in the title
the following titles in anime-titles.xml (anidb title database) could fail matching as a result or grouped with the first season:: 
YUA TV3 / YUA TV2 / YUA TV1 (biggest impacted)
Duel Masters Victory V3
Kigurumikku V3
DBMV3
GitSv2
r+v2/rtv2
UBWTV2
v2s
El Hazard TV 2 / elhaz tv2 (only short name impacted)
ranmov2
gbtv2

That sais, in function  clean_filename i remove such strings so will implement in regex to remove  clean_filename v1/2/3 references and not put it in pre whack, which is extremely drastic

Do you agree with that ?

I have completed the X-Plex-Token.id file support with web token inside to create a log per library with the associated filelist... you can mail me at benjamin.brisson@gmail.com while forum is down or through github

**Comment by ZeroQI** [comment]
Try this regex instead and let me know.
  '^((?P<show>.*?)[ _\.\-]+)?(?!S|SP|(NC)?OP|(NC)?ED|PV)(e|ep|e |ep |e-|ep-)?(?P<ep>[0-9]{1,3})((v2|v3|v4|v5)|(e|ep|-e|-ep|-)(?P<ep2>[0-9]{1,3}))?(( | - )(?P<title>.*?))?$']      #  5 # E01 | E01-02| E01-E02 | E01E02 
if works i will remove the v1/v2/v3 code in the rename to let the regex handle

**Comment by ZeroQI** [comment]
modifying word processing and regex to support versions

**Comment by magnumdoomguy** [comment]
Great!  Thanks!

**Comment by ZeroQI** [comment]
try latest version i uploaded
try to create a file X-Plex-Token.id in logs folder with the url plex token inside and it create a log per library

**Comment by magnumdoomguy** [comment]
New version works -- all version numbered episodes are picked up.

I noticed a small potential issue with the new logging stuff.   On line 127 you have the port number hard-coded in.  Since it's possible to change the port number manually in the server settings (and in special cases necessary), that would cause that part of the code to fail for people not using the default port number.

**Comment by ZeroQI** [comment]
Excellent.
Should i rather put the full url in the file then?

**Comment by ZeroQI** [comment]
no place contain this direct link it  
Thanks for bringing it to my attention but will leave as it is in the meantime.
Anything else in the scanner needs fixing ?

**Comment by ZeroQI** [comment]
Closing

**Comment by ZeroQI** [comment]
Can you please try latest scanner and latest agent (*__init__.py and *
DefaultPrefs.json
<https://github.com/ZeroQI/Hama.bundle/blob/master/Hama.bundle/Contents/DefaultPrefs.json>
)
I would apreciate a test of the anidb apostrophe, and of the specials
summary. both should be resolved

any error, please let me know and paste the errors together with the last
few lines of log output

Regards,
Benjamin

**Pull request closed without merging**
