### PR TITLE
Multiple Updates

### PR DESCRIPTION
**Pull request by EndOfLine369**
* Removal of series name from filename includes additional "folder_show" matches ( clean; clean wo/parenthesis; clean wo/dash; clean wo/parenthesis&dash) https://github.com/ZeroQI/Hama.bundle/issues/41 Issue 2
* Move of 4digit processing after string instance count when there is a legit 4digit number in the series name https://github.com/ZeroQI/Hama.bundle/issues/41 Issue 3
* Removal of ' ' & '-' in lstrip call from remaining filename when striped of the series name https://github.com/ZeroQI/Hama.bundle/issues/41 Issue 4
* Fix parsing of AniDB specials incorrectly seeing files with seasons strings in the name (EX: "Dog Days S3 - ED1" incorrectly as s0e3)
* Clean episode titles of parenthesis to remove any incomplete whack
* Additional cleaning in filename & series name matching for ep 01 assignment
* Nesting of single file checks to skip tests when 2+ files
* Special "picture drama" string matching changed from "startswith" to "in" as series name is not always able to be removed to make it be at the start of the filename
* Correct previous pre-whack additions

### CODE REVIEW

**Comment by EndOfLine369** [comment]
@ZeroQI please peer review/test

**Comment by ZeroQI** [comment]
Very nice work :D

The only point of contention i have is The special anidb convention Sxx gave me issues in the past as it conflicted partially with the Sx season numbering in titles

At the time the decision i made was to support anidb numbering, because nyatorrent and some other hi10p torrent use anidb convention and op ed specials in the torrent and i want to not have to modify filenames, and series that have Sx in the title due to the season are rare, some of which are synonyms hence not following anidb naming convention, and it is easier to fix a folder name than the folder files time wise and organisation wise...

I though i had it coded but apparently it's not in the code...
By removing the serie name word by word for the word loop used to find the ep number, then remove the Sx from ep name if in a season folder, then most cases will be handled. (isn't Sx scrubbed already if the folder name contain it ?)

then use what is on the right of the ep number found to get the title without removing parenthesis as some titles have it... (should be current behaviour)

**Comment by EndOfLine369** [comment]
Comments on your concerns/points: :space_invader: 
:small_blue_diamond: I did not remove the ability to match SX episodes. Only the order of matching. By simply moving the "Sx" matching to the end of the regex strings, it allows the other specials to be matched first and thus allow any "Sx' in the filename to be skipped.
:small_blue_diamond: There are other reasons the folder name will not match the filename. (1) the filenames are in jap and foldername is in english (2) people use the foldername to store additional info (none of mmine ever do as i use it to store both the eng & jap name, series episodes, anidb num, ann num, stars, watching status)
:small_blue_diamond: The word for word loop already protects against seeing 'S2' as s0e2 from the instance count breach as 'S2' will be in multiple/all filenames even if it is not removed by the folder name trim. It was only the regex that was not handling the season 'Sx' in the filename. It has no multiple instance ignore setup and not the folder name trim (which can still not always match).
:small_blue_diamond: There were multiple instances where the whack is incomplete. And the nature of everyone using their own way just makes it too random for us to ever get them all. By clearing out the parenthesis from the title, it allows us to better make sure no gibberish is put into Plex. I would say it is better to have some strings missing than adding in easily visible crap names into Plex. Especially when it is not able to match the episode and have the title overwritten with metadata which is default for 501+ specials.

**Comment by ZeroQI** [comment]
My bad.
Last point, you can remove strings to find ep number then reuse it to use a less aggressive cleanup keeping parenthesis for the titles on whatever is on the right of it. Will get updated by the agent but will be ahowing in the meantime. Good for unrecognised ep titles
Very descriptive answer ince again. Thanks a lot

**Comment by EndOfLine369** [comment]
Sry, I don't think I follow. Are you saying to basically go back to the filename, find the index of of the ep string we use, then take everything to the right of that as the episode title? That would mean including all bracked info, whacked info, filter chars, everything... as the episode title. I see that as worse than leaving it as it is currently with a normal clean. 

It should be rare that an episode name has parenthesis in the title & that the file also has that in the filename & is not able to get meteadata loaded (500+ ep). As if they want the info in Plex, they can update the filename with the correct special string for it to get loaded with metadata and thus not be a 500+ episode. In the meantime, it would not have ugly non-whackable strings in the title.

**Comment by ZeroQI** [comment]
The way we do know is fine.
I want a hard clean to fin the ep number then if found we find the index of of the ep string we use, then take everything to the right of that and do a soft clean which keeps parenthesis on that part.

This way no impact on functionalities
It is the way it is done currently except it uses the words array hence parenthesis are scrubed from titles when it doesn't the ep number search, just impact ep titles

**Comment by EndOfLine369** [comment]
Looks like we can't agree on this so I concede as this has no impact in how files are processed.

**Comment by ZeroQI** [comment]
I agree unconditionally to all other changes. It does not impact how files are processed, only titles for episodes which are updated by the agent and generally absent and if present, would be used as is (like the ones generated with JMM).
If there is garbage filtering through, feel free to apply the changes you reverted.

Thanks for your assistance which is much appreciated.
I feel like sometimes you know the code better than i do

**Pull request merged**
