### PR TITLE
Allow YouTube playlists larger than 50 videos

### PR DESCRIPTION
**Pull request by jjanusch**
While testing the scanner, I noticed that trying to scan any YouTube playlists with more than 50 videos in them would result in any video after the 50th in the playlist (even if you only had video 55 in your files) not being imported into Plex.

The cause of this was the YouTube API limiting the number of video items that can be pulled via one request. See [PlaylistItems: list](https://developers.google.com/youtube/v3/docs/playlistItems/list#parameters) documentation, specifically the `maxResults` parameter:

> Acceptable values are 0 to 50, inclusive. 

This patch adds a while loop that continues to run if it finds `nextPageToken` in the results, and requests that next page in the next iteration. I included a hard stop at 1000 videos (see `youtubeRequestLimit` variable) to prevent infinite loops.

I haven't worked with Python in close to a decade (I'm primarily PHP and JS), so I apologize if my code is a bit rough/ugly.

### CODE REVIEW

**Comment by ZeroQI** [comment]
Noticed it yesterday and adding channel support too. Coding the agent at the same time to bring all changed together. Will use part of your code. Failsafe is a good idea.

Was thinking of using optionally the year as season for channels... What do you think?

**Comment by ZeroQI** [comment]
i was considering [youtube2-xxxxxxxxxxxx] format to use years as season.
Plex use a year or a season number, no season text but season folders on disk can have any title afterwards...

There is no season or episode number. it is part of the title but not recorded as such
'Basics With Babish' does create playlist per season though...

That is imported ok by the scanner already:
- Library Root/Binging With Babish [UCJHA_jMfCvEnv-3kRjTCQXw]/(Season 01/)Basics With Babish - S01E16 [E_8wQsmjn0A].mp4

To be clear, i check per YouTube video id the information so it needs to be in the filename in brackets.
Any season or episode arrangement should be supported. 

Not sure i should keep playlist on season folders though

**Comment by ZeroQI** [comment]
https://developers.google.com/youtube/v3/docs/search/list

The videoType parameter lets you restrict a search to a particular type of videos. If you specify a value for this parameter, you must also set the type parameter's value to video.

Acceptable values are:
any – Return all videos.
episode – Only retrieve episodes of shows.
movie – Only retrieve movies

**Comment by djmixman** [comment]
> As a sidenote, for many YouTube series, there are actual Seasons and Episode numbers. If you look at this Binging with Babish video, you'll see it is BASICS WITH BABISH S1 • E16. Would it be possible to do a more traditional structure? Something like this:

From my experience a lot of Youtubers don't seem to use this, especially the gamers. 

----

The issue i'm running into on this is the scanner not finding a episode within its title and automatically getting kicked over into the special season. This in turn breaks the play order of the series. 

Using playlists is great, when they are properly maintained and setup correctly, however there are some playlists that are reversed and also will not play in the proper order within plex. See https://www.youtube.com/watch?v=t3kIptC3Zhg&list=PLLLYkE3G1HED6rW-bkliHbMroHYFf4ukv for example. 

I've done a bit of testing and the best solution I could come up with would be to use the year as the season and then for the episode number is the day number and time. Unless there is a file uploaded within the same minute of each other then there won't be an issue. This method also does not have to rely on a youtube playlist to sort files and organize files, but can still be used for some extra metadata. In my option I think the following should probably be the default for any youtube related processing.

Videos would be listed as:

Season YYYY Episode DDDHHMM
Where as DDD being the current day number of the year. 

So 2018-05-13T23:40:03 would translate to 

Season 2018 Episode 1332340
Yes, ugly as shit I know, but it covers almost any use case from Youtube that I have found so far. 

All this can be computed from the metadata received from youtube on the video, however as this script becomes more popular you will have to have people use their own API key since it will be hitting the youtube limit (happened last night during my testing).

It's quite ugly but works well in keeping everything playing in the correct order. As said before it does not rely on playlists so this method can carry over to custom sub-folders for youtubers that are too lazy to create or keep their playlists up to date (i'm looking at you Delirious 😠)

**Comment by ZeroQI** [comment]
@jjanusch Thanks for the code. i used it to do an update but chose to not import directly you code to allow >50 videos but is now already implemented now so closing that pull request
Please use https://github.com/ZeroQI/Absolute-Series-Scanner/issues/163 to continue the discussion

I checked the YouTube API doing multiple calls, some videos have a type set as 'episodes' but no season or episode number given asides from the title

Will evolve the scanner to allow playlist and chan id, and a youtube2 mode to allow season as folders and date based, numbered sequentially from the files on disks

**Pull request closed without merging**
