### PR TITLE
Fixing a typo in line 997

### PR DESCRIPTION
**Pull request by rotelok**

### CODE REVIEW

**Comment by ZeroQI** [comment]
I made a typo indeed, thanks for spotting.
(int)(ep) or int(ep)) to fix? Am more for the latter

**Comment by rotelok** [comment]
here I used (int)(ep) and it seems to work, but my python knowledge is not the best

**Comment by rotelok** [comment]
the error was:
  File "Absolute Series Scanner.py ", line 997
    if   ep.isdigit() and len(ep)==4 and (int(ep)>= 1930: filename = clean_string( " ".join(words).replace(ep, "(%s)" % ep));   continue                                           # take everything after supposed episode number
                                                        ^
SyntaxError: invalid syntax

**Comment by ZeroQI** [comment]
"(int(ep)" have mismatch parenthesis, my bad.
"int(ep)" was the intent
"(int)(ep)" is suggested which is legal but note sure it convert to int the string but may declare it as int

**Comment by ZeroQI** [comment]
corrected in the source directly. Thanks for spotting the typo

**Pull request closed without merging**
