### PR TITLE
Major Update: Addition of 'anidb3' & 'anidb4' mode

### PR DESCRIPTION
**Pull request by EndOfLine369**
**Hey @ZeroQI,**

So.....in the work of updating my anime entries over to 'anidb2' mode setup to combine related series animes, I was hit with an issue on multiple TVDB series setups.
The issue was that TVDB had some sequel/prequel entries annoyingly listed as season 0 specials.

I started to try and write custom ScudLee mapping for each I was seeing to move them out of season 0. But I found too many and was concerned I might be missing some (I was). So I have now codded it into the scanner to fix these entries automatically as mode 'anidb3'.

----

### 'anidb3' - Uses ScudLee mapping to map the AniDB series to TVDB entries BUT overrides the mapping for TVDB season 0 entries and puts them in AniDB relational order by appending to existing seasons or adding new seasons at after the last TVDB season

**NOTE**: AniDB series that are prequels to the series that is mapped to TVDB season 1 will stay as specials.

**NOTE**: Episode metadata will be blank for those adjusted series episodes till HAMA is updated to handle this new mode.

### Example of "Date a Live":
In AniDB its relation map [HERE](http://anidb.net/perl-bin/animedb.pl?show=rel&aid=8808) has:
```
1. Date a Live (a8808)
2. Date a Live: Date to Date (a9734)
3. Date a Live II (a9935)
4. Date a Live II: Kurumi Star Festival (a10568)
```
But in the TVDB entry [HERE](https://www.thetvdb.com/series/date-a-live/seasons/all) it has that sequel/prequel placement mapped as:
```
TVDB s1   = Date a Live (a8808)
TVDB s0e1 = Date a Live: Date to Date (a9734)
TVDB s2   = Date a Live II (a9935)
TVDB s0e2 = Date a Live II: Kurumi Star Festival (a10568)
TVDB s3   = TBD (prep entry in TVDB)
```
So when I put all 4 series as mode 'anidb2', it uses the ScudLee mapping as expected.
But that annoyingly puts the AniDB entries out of order for proper sequential viewing in Plex. 
So you would have to remember to go back and forth from season 0 to watch it in the correct order. (S1->S0->S2->S0) 💢 

This mode will correct that order jumping by applying adjustments to those TVDB season 0 entries using AniDB (sequel/prequel) relation mapping.

(Note: This was pulled from inline code comments so code has documentation on the what/why)
**Step 1** - It will still do the same 'anidb2' ScudLee mapping info.
**Step 2** - If the series is listed as 'defaulttvdbseason' == '0' loaded from step 1, it will now try to figure out if it should truly be there and need to update the loaded mapping info.
Else, it will not to anything and skip Step 3 and do nothing to the mapping and just act as if it was in 'anidb2' mode
**Step 3** - Check if it needs to to update the mapping:
- Load in ScudLee & ASS mapping again and merge them
- Find each entry that has the same tvdbid listing and store its max season#
- Get the max season number from TVDB for the tvdb id
- Set the max season for a series with 'defaulttvdbseason' == 'a'
- Generate a relations map using all anidbid's using the same tvdbid stored earlier
- Recursively go down the tree following prequels using the relations map
-- If the prequel is a tvdb special as well, check its' prequel
-- Else:
--- Root prequel is a special so leave as special
--- Root prequel season is < max season so add to the end of the Prequel season (adding 100 to the episode offset)
--- Root prequel season is >= max season so add to the season after max
- If the root prequel is not a special, it will clear out all 'mappingList' 's1*' mapping entries and update the 'defaulttvdbseason' & 'episodeoffset' with the new values. As only 's1' entries are cleared out, all anidb special mapping still gets applied.

So in practice, that turns the "Date a Live" entries to:
```
#### FROM: ####
s1   - Date a Live (a8808)
s0e1 - Date a Live: Date to Date (a9734)
s2   - Date a Live II (a9935)
s0e2 - Date a Live II: Kurumi Star Festival (a10568)
s3   - TBD (prep entry in TVDB)
#### TO: ####
s1     - Date a Live (a8808)
s1e101 - Date a Live: Date to Date (a9734)
s2     - Date a Live II (a9935)
s2e101 - Date a Live II: Kurumi Star Festival (a10568)
```
### MORE EXAMPLES:
**"Baka and Test: Summon the Beasts"**
http://anidb.net/perl-bin/animedb.pl?show=rel&aid=6747
https://www.thetvdb.com/series/baka-and-test-summon-the-beasts/seasons/all
```
#### FROM: ####
s1       - Baka to Test to Shoukanjuu (a6747)
s0e09/10 - Baka to Test to Shoukanjuu: Matsuri (a8085)
s2       - Baka to Test to Shoukanjuu Ni! (a8235)
#### TO: ####
s1         - Baka to Test to Shoukanjuu (a6747)
s1e101/102 - Baka to Test to Shoukanjuu: Matsuri (a8085)
s2         - Baka to Test to Shoukanjuu Ni! (a8235)
```

**"Ranma ½"**
http://anidb.net/perl-bin/animedb.pl?show=rel&aid=193
https://www.thetvdb.com/series/ranma-1-2/seasons/all
```
#### FROM: ####
s1          - Ranma 1/2 (a4576)
s1->s7      - Ranma 1/2 Nettou Hen (a193)
s0e03->08   - Ranma 1/2 (1993) (a405)
s0e09/10    - Ranma 1/2 Special (a2995)
s0e11       - Ranma 1/2: Chou Musabetsu Kessen! Ranma Team VS Densetsu no Houou (a2850)
s0e12/13/14 - Ranma 1/2 Super (a2996)
#### TO: ####
s1     - Ranma 1/2 (a4576)
s1->s7 - Ranma 1/2 Nettou Hen (a193)
s8     - Ranma 1/2 (1993) (a405)
s9     - Ranma 1/2 Special (a2995)
s10    - Ranma 1/2: Chou Musabetsu Kessen! Ranma Team VS Densetsu no Houou (a2850)
s11    - Ranma 1/2 Super (a2996)
```

**"Maken-Ki! Battling Venus"**
http://anidb.net/perl-bin/animedb.pl?show=rel&aid=8265
https://www.thetvdb.com/series/maken-ki-battling-venus/seasons/all
```
#### FROM: ####
s1   - Maken-ki! (a8265)
s0e7 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s0e8 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s2   - Maken-ki! Two (a9406)
#### TO: ####
s1     - Maken-ki! (a8265)
s1e101 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s1e201 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s2     - Maken-ki! Two (a9406)
```

----

### 'anidb4' - Uses ScudLee mapping to map the AniDB series to TVDB entries BUT overrides the mapping for TVDB seasons entries and puts them in AniDB relational order by inserting new seasons and pushing later TVDB seasons back

Same as 'anidb3' ordering. But instead of adding in series at the end of existing seasons, it will create a new season and push all later tvdb seasons back.

**NOTE**: AniDB series that are prequels to the series that is mapped to TVDB season 1 will stay as specials. Do any even exist? This mode could potentially make season 1 the root prequel. Let me know if there is a case/example of this being true.

**NOTE**: As no HAMA setup yet for the 'tvdb6' merged mode from 'anidb4', it will be worse than 'anidb3' that just had missing episode info.

### EXAMPLES:
```
#### FROM: ####
s1   - Date a Live (a8808)
s0e1 - Date a Live: Date to Date (a9734)
s2   - Date a Live II (a9935)
s0e2 - Date a Live II: Kurumi Star Festival (a10568)
s3   - TBD (prep entry in TVDB)
#### TO: ####
s1 - Date a Live (a8808)
s2 - Date a Live: Date to Date (a9734)
s3 - Date a Live II (a9935)
s4 - Date a Live II: Kurumi Star Festival (a10568)
```
```
#### FROM: ####
s1       - Baka to Test to Shoukanjuu (a6747)
s0e09/10 - Baka to Test to Shoukanjuu: Matsuri (a8085)
s2       - Baka to Test to Shoukanjuu Ni! (a8235)
#### TO: ####
s1 - Baka to Test to Shoukanjuu (a6747)
s2 - Baka to Test to Shoukanjuu: Matsuri (a8085)
s3 - Baka to Test to Shoukanjuu Ni! (a8235)
```
```
#### FROM: #### (unchanged from 'anidb3')
s1          - Ranma 1/2 (a4576)
s1->s7      - Ranma 1/2 Nettou Hen (a193)
s0e03->08   - Ranma 1/2 (1993) (a405)
s0e09/10    - Ranma 1/2 Special (a2995)
s0e11       - Ranma 1/2: Chou Musabetsu Kessen! Ranma Team VS Densetsu no Houou (a2850)
s0e12/13/14 - Ranma 1/2 Super (a2996)
#### TO: ####
s1     - Ranma 1/2 (a4576)
s1->s7 - Ranma 1/2 Nettou Hen (a193)
s8     - Ranma 1/2 (1993) (a405)
s9     - Ranma 1/2 Special (a2995)
s10    - Ranma 1/2: Chou Musabetsu Kessen! Ranma Team VS Densetsu no Houou (a2850)
s11    - Ranma 1/2 Super (a2996)
```
```
#### FROM: ####
s1   - Maken-ki! (a8265)
s0e7 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s0e8 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s2   - Maken-ki! Two (a9406)
#### TO: ####
s1 - Maken-ki! (a8265)
s2 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s3 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s4 - Maken-ki! Two (a9406)
```

----

### Scanner can be pulled down from here if anyone wants to test it out before merge.
https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/EndOfLine369-anidb3/Scanners/Series/Absolute%20Series%20Scanner.py

### CODE REVIEW

**Comment by EndOfLine369** [comment]
Scanner can be pulled down from here if anyone wants to test it out before merge.
https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/EndOfLine369-anidb3/Scanners/Series/Absolute%20Series%20Scanner.py

Note that metadata will be blank for those adjusted series episodes till HAMA is updated to handle this new mode.

**Comment by ZeroQI** [comment]
@EndOfLine369 That reminds me of tvdb5 mode. 
You did manage to move end of season specials to their righfull place which is a Plex limitation, nice!
Here are my thoughts on the mode
- Should the ep numbering be in sequence instead of ep 100+? in sequence would look better IMO as some release/people put specials as ep 25/26 after normal eps...
- should mid season specials be handled? tvdb episodes json include fields ("airsAfterSeason","airsBeforeSeason","airsBeforeEpisode") which would allow mid season and pre season specials insertions which anidb relation graph doesn't do. summary will need to reflect special status.  The series should then be presented as tvdb 6 mode to HAMA? will have to re-process both anidb and tvdb dict to shift ep...

**Comment by ZeroQI** [comment]
@EndOfLine369 Magistral answer as always. Makes perfect sense.
We ciuld also have a season per Anidb series instead but that would be so messy agent side I guess...
I have the knowledge thanks to Lambda to update season summary but am short in free time due to house being built as we speak... Also need to finish Lambda agent as it was commissioned and then I can update Hama to match.

**Comment by EndOfLine369** [comment]
**"We could also have a season per Anidb series instead"**
Yeah, had thought about that possibilitym when I was deciding where to put the episodes. Where instead of putting it at the end of the unchanged tvdb season, it would insert it as a new season between existing ones and push other seasons back.
IE:
```
#### FROM: ####
s1   - Maken-ki! (a8265)
s0e7 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s0e8 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s2   - Maken-ki! Two (a9406)
#### TO: ####
s1 - Maken-ki! (a8265)
s2 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s3 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s4 - Maken-ki! Two (a9406)
```
I could potentially write that as a 'anidb4' where it is AniDB series relational order and each series gets its own season. This would definitely require more mapping rework potentially on all season info from TVDB and not just special's info... THAT would require a 'tvdb6' source id merging as that new season setup would not work with any other mode listings like 'tvdb3' & 'tvdb4' can't work with any other mode listings. 
I had wanted to avoid that so went with the placement setup I did so this new mode will with the other modes ('anidb2'/'anidb3'/'tvdb'/'tvdb2' will work together).

**Comment by EndOfLine369** [comment]
Have actually just codded this 'anidb4'->'tvdb6' mode. 😄
Initial testing all passes ✔️. Will do additional testing before committing here.

**Comment by EndOfLine369** [comment]
Just committed 'anidb4' 😄 
**NOTE**: As no HAMA setup yet for the 'tvdb6' merged mode for 'anidb4', it will be worse than 'anidb3' that just had missing episode info. This will currently fail to match & merge the ids.

**Comment by EndOfLine369** [comment]
@sven-7, very possibly. I don't have that series so have not tested myself. Please try.

**Comment by sven-7** [comment]
Okay, sweet - I'll read the documentation and give it a go this weekend. Will let you know how it goes.

**Comment by EndOfLine369** [comment]
### 'anidb4' - Uses ScudLee mapping to map the AniDB series to TVDB entries BUT overrides the mapping for TVDB seasons entries and puts them in AniDB relational order by inserting new seasons and pushing seasons back

Scanner can be pulled down from here if anyone wants to test it out before merge.
https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/EndOfLine369-anidb3/Scanners/Series/Absolute%20Series%20Scanner.py

**NOTE**: As no HAMA setup yet for the 'tvdb6' merged mode from 'anidb4', it will be worse than 'anidb3' that just had missing episode info. This will currently fail to match & merge the ids.

### EXAMPLES:
```
#### FROM: ####
s1   - Date a Live (a8808)
s0e1 - Date a Live: Date to Date (a9734)
s2   - Date a Live II (a9935)
s0e2 - Date a Live II: Kurumi Star Festival (a10568)
s3   - TBD (prep entry in TVDB)
#### TO: ####
s1 - Date a Live (a8808)
s2 - Date a Live: Date to Date (a9734)
s3 - Date a Live II (a9935)
s4 - Date a Live II: Kurumi Star Festival (a10568)
```
```
#### FROM: ####
s1       - Baka to Test to Shoukanjuu (a6747)
s0e09/10 - Baka to Test to Shoukanjuu: Matsuri (a8085)
s2       - Baka to Test to Shoukanjuu Ni! (a8235)
#### TO: ####
s1 - Baka to Test to Shoukanjuu (a6747)
s2 - Baka to Test to Shoukanjuu: Matsuri (a8085)
s3 - Baka to Test to Shoukanjuu Ni! (a8235)
```
```
#### FROM: #### (unchanged from 'anidb3')
s1          - Ranma 1/2 (a4576)
s1->s7      - Ranma 1/2 Nettou Hen (a193)
s0e03->08   - Ranma 1/2 (1993) (a405)
s0e09/10    - Ranma 1/2 Special (a2995)
s0e11       - Ranma 1/2: Chou Musabetsu Kessen! Ranma Team VS Densetsu no Houou (a2850)
s0e12/13/14 - Ranma 1/2 Super (a2996)
#### TO: ####
s1     - Ranma 1/2 (a4576)
s1->s7 - Ranma 1/2 Nettou Hen (a193)
s8     - Ranma 1/2 (1993) (a405)
s9     - Ranma 1/2 Special (a2995)
s10    - Ranma 1/2: Chou Musabetsu Kessen! Ranma Team VS Densetsu no Houou (a2850)
s11    - Ranma 1/2 Super (a2996)
```
```
#### FROM: ####
s1   - Maken-ki! (a8265)
s0e7 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s0e8 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s2   - Maken-ki! Two (a9406)
#### TO: ####
s1 - Maken-ki! (a8265)
s2 - Maken-ki!: Natsu Da! Mizugi Da! Gasshuku Da! (a8566)
s3 - Maken-ki! Two: Takeru Nyotaika!? Minami no Shima de Supoon (a10191)
s4 - Maken-ki! Two (a9406)
```

**Comment by ZeroQI** [comment]
Monogatari collection is the worst anime possible to sort an thus the best example for this.
I can see benefits to both modes.
Let's ensure scanner-wise it maps correctly and then Hama will need amending.
I am up to my eyeballs at the moment so want to avoid coding if you are doing it, but will assist, so EndOfLine369, if you need me to do any issue or if i am to code Hama part, let me know.

**Comment by EndOfLine369** [comment]
@sven-7, I do not know your folder setup. Just label it all as either anidb3 or anidb4 (they do not work together) through foldername entry or '*.id' files as you would for any other setups you do.

**Comment by sven-7** [comment]
Here's how I have it set up right now with test files.  I think I might be missing a piece of how it's supposed to be put together. 

[Bakemonogatari.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2409129/Bakemonogatari.zip)

**Comment by EndOfLine369** [comment]
At first glance, not sure how any of that would ever work with any mode let alone this one. You have a top folder 'anidb3.id' for all your anime listings as a grouping folder trying to define the same 'a6327' (which is not a valid id) for all.

**Comment by EndOfLine369** [comment]
Ignoring the bad filenames for correct numbering, this is what you get with the files you provided.

----

### EX: anidb3
image

image

----

### EX: anidb4
image

image

**Comment by EndOfLine369** [comment]
'anidb3' seems to be your best option due to 'Owarimonogatari' being listed as season 4 but not actually a sequel to the true series

**Comment by EndOfLine369** [comment]
Hey @ZeroQI, note that I have little knowledge of hama as it is now. Been running on old versions of the scanner and agent (still am). Only a month ago did I try to use the new ass version which prompted all the bug fixes/updates. hama has yet to be used/reviewed. So at time time I can only reasonably fix simple bugs (already fixed one). It will probably be quite some time for me to fully grasp the new coding & logging output to be able to enhance it.

**Comment by sven-7** [comment]
Thanks, @EndOfLine369!  It's such a messy show that I may just opt to keep it as I have. There likely isn't a perfect solution out there. I think my ideal solution would be to have the individual shows broken up as seasons in the order they were released. I don't think it's worth having a custom mapping file function as this show is largely an anomaly, in my opinion.  

[I've been going off of this list](https://recommendmeanime.com/watch-monogatari-series-order/):

> **Release Order – Recommended Watching Order for First-Time Monogatari Watchers**
> 
> - Bakemonogatari – Contains the stories Hitagi Crab, Mayoi Snail, Suruga Money, Nadeko Snake, and Tsubasa Cat.
> - Nisemonogatari – Contains the Karen Bee and Tsukihi Phoenix stories.
> - Nekomongatari: Kuro – Tells the prequel story of the Tsubasa family.
> - Monogatari Series: Second Season – Somewhat confusingly named if you have no experience with the light novels, this encompasses a big bulk of the single story light novels including the Tsubasa Tiger, Mayoi Jiangshi, Nadeko Medusa, Shinobu Time, and Hitagi End.
> - Hanamonogatari – Tells the Suruga Devil story.
> - Tsukimonogatari – Tells the Yotsugi Doll story.
> - Owarimonogatari (First Season) – Tells the Ougi Formula, Sodachi Riddle, Sodachi Lost, and Shinobu Mail stories.
> - Koyomimonogatari – Encompasses 12 different short stories about Koyomi.
> - Owarimonogatari (Season 2) – Tells the Hitagi Rendezvous, Araragi Koyomi’s story, and Ougi Dark stories as well as one other story not mentioned for spoilers sake.

**Comment by ZeroQI** [comment]
@EndOfLine369 I must say Hama is a bit of a gas factory, but I tried to keep things simple.
- The naming convention is anidb unless multiple seasons or tvdbid.
- Functions allow to map from one numbering to the other.
- Funky stuff to make languages work first then the metadata source
- did the listing of ep detected in logs for AniDB and Hama, must say logs look good.
I will do my bit for Hama then but need Lambda finished, nearly there, and I keep you posted
That said, the tvdb modes are unique to Plex and I tried to make it the best ecosystem and didn't think the scanner would be popular. I am grateful for your kind assistance in making it better, especially as my free time is shrinking with a house being build as we speak. I keep you posted when Lambda is done, hopefully within a week or two, will do my best...

**Comment by EndOfLine369** [comment]
@ZeroQI, btw i'm trying to update HAMA. Taking it as a opportunity to read the code and understand it a bit. 👍

**Comment by EndOfLine369** [comment]
@ZeroQI,
Please review/comment/test.
https://github.com/ZeroQI/Hama.bundle/pull/249
https://github.com/ZeroQI/Hama.bundle/archive/EndOfLine369-anidb34.zip

**Comment by ZeroQI** [comment]
Thanks. Had tried compressing the regex but failed. Solve 100+ YouTube playlist issues

**Pull request merged**
