### PR TITLE
Multiple Updates

### PR DESCRIPTION
**Pull request by EndOfLine369**
* Fix anidb_rx index numbers in comments
* Update 'clean_string' for dot num specials so it does not start with a season/special char 'S|s' (s2.03) or a version char 'v' (v1.2)
* Update 'thetvdb.com' url pull to https
* Add 'Movies' setting if only one file in the folder & contains '-m' in the folder name denoting a movie folder
* Add 'Movies/Single EP Shows' setting if only one file in the folder & it has no numbers in it (as would otherwise force it to a 500+ special)
* Add commented log statements for easier debugging when needed
* Update string with '-' parsing to only split if the string is only seen once when more than one file & not in the folder_show 
* Update specials match to include most special strings to break out for regex filename processing
* Fix folder season check on 4digit string test 'int(ep[0:1])==folder_season' to 'int(ep[0:2])==folder_season)' as was incorrectly only using the first char only
* Update to reduce the 'misc.count(ep)>=3' down to 'misc.count(ep)>=2'
* Update to prefix parsing test of 'ep[len(prefix):].isdigit()' to 're.match("^\d+(.\d+)?$", ep[len(prefix):])' so it can handle dot num specials (EX: 12.5)
* Update to dot num special parsing to be after exclusion testing of repeated entries (EX: required for 'Tokyo Magnitude 8.0')
* Minor code comment updates

### CODE REVIEW

**Comment by EndOfLine369** [comment]
@ZeroQI Here we are. Please review. :smiley: 
This will allow you to better see the change diffs per each addition/update/fix.

**Comment by ZeroQI** [comment]
Look good to me, like the diff

**Comment by ZeroQI** [comment]
Dunno how you did nut the multiple commits in one release look great.

**Comment by EndOfLine369** [comment]
To get this multi commit, you create a single commit w/ a pull request. Once that has been created, navigate to the "Files changed" tab and click the edit icon.

image

Once you have made your additional changs, save them and apply them to the same 'patch-X' branch.

Every commit made to the branch will show in the same pull request.

**Comment by EndOfLine369** [comment]
Its how you can get people to fix proposed code before a pull is made so you don't have to outright reject the pull request and make them resubmit with the changes you require.

**Comment by EndOfLine369** [comment]
I just used this as a way of submitting a single pull with multiple commits instead of multiple pull requests with a single commit.

**Pull request merged**
