### PR TITLE
Filebot Xattr support attempt

### PR DESCRIPTION
**Pull request by ZeroQI**
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/262

### CODE REVIEW

**Comment by IIeTp** [comment]
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4420719/Plex.Media.Scanner.log)

Did not work. There are no other logs.

**Comment by IIeTp** [comment]
checked. same error

**Comment by ZeroQI** [comment]
need other fixes... will look into it

**Comment by IIeTp** [comment]
Scanner ignores information from .xattr.
What is the priority for data from .xattr?

I used a modified .xattr for another TV show, but the scanner did not use this information.

**Comment by ZeroQI** [comment]
Takes the forced id first, and if not present the Xattr (if xattr files present)

**Pull request merged**
