### PR TITLE
Scanner Updates

### PR DESCRIPTION
**Pull request by EndOfLine369**
Hi @ZeroQI,

Updates are broken down into commits.
I think I've hit the last I can fix/tweak for the current scanner. 😄 

`Update "File main loop"`:
Reason for this was this instance I had below. I have 4 different copies of episode 1 so '01' was in 'misc_words'. Thus it was filtered out of the filename so all episodes had no episode number and all were being hit as s0e5XX.

```
=============================================================================================================================================================
Forced ID (series folder) - source: "tvdb", id: "303867-s1e11"
offset_season = 0, offset_episode = 10
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'ni': 4, '01': 4, 'Shukufuku': 4, 'Kono': 4, 'Subarashii': 4, 'Sekai': 4, 'wo!': 4}
misc_words: ['Subarashii', 'Shukufuku', 'Sekai', 'Kono', 'wo!', 'ni', '01']
[All files were seen as unknown(5XX). Trying one more time without miscellaneous string filtering.]
"Kono Subarashii Sekai ni Shukufuku o! Kono Subarashii Choker ni Shukufuku o! [tvdb-303867] -f -lj -s9 -e1 -a11854 [anidb2-11854] -n0" s01e011                         "SERIES_RX-2" "" "[Chihiro]_Kono_Subarashii_Sekai_ni_Shukufuku_wo!_-_01_[Blu-ray_720p_Hi10P_FLAC][48292DEE].mkv"
"Kono Subarashii Sekai ni Shukufuku o! Kono Subarashii Choker ni Shukufuku o! [tvdb-303867] -f -lj -s9 -e1 -a11854 [anidb2-11854] -n0" s01e011                         "SERIES_RX-2" "" "[Chihiro]_Kono_Subarashii_Sekai_ni_Shukufuku_wo!_-_01_[Blu-ray_1080p_Hi10P_FLAC][61DCE29A].mkv"
"Kono Subarashii Sekai ni Shukufuku o! Kono Subarashii Choker ni Shukufuku o! [tvdb-303867] -f -lj -s9 -e1 -a11854 [anidb2-11854] -n0" s01e011                         "SERIES_RX-2" "(11)" "[FFF] Kono Subarashii Sekai ni Shukufuku wo! - 01 (11) [BD][720p-AAC][8D228B15].mkv"
"Kono Subarashii Sekai ni Shukufuku o! Kono Subarashii Choker ni Shukufuku o! [tvdb-303867] -f -lj -s9 -e1 -a11854 [anidb2-11854] -n0" s01e011                         "SERIES_RX-2" "(11)" "[FFF] Kono Subarashii Sekai ni Shukufuku wo! - 01 (11) [BD][1080p-AAC][4C6D7F90].mkv"
=============================================================================================================================================================
```

Easier view to the commit diff when the ignore white space setting added:
https://github.com/ZeroQI/Absolute-Series-Scanner/pull/182/commits/c8451d6c6c74cd66f53d707d866d4f5e8762f79d?utf8=%E2%9C%93&diff=unified&w=1

### CODE REVIEW

**Comment by ZeroQI** [comment]
@EndOfLine369 Thanks a lot, it is better, especially File main loop. I am really happy with all the coding you did and only 1 commit however needs to be crashed, as plex indicates "Always use forward-slashes (/) as path delimiters, even on Windows". I first thought 'good catch' until i re-checked the recommendations for the format...
Thanks again for your assistance again

**Comment by EndOfLine369** [comment]
Reverted the plexignore changes. Tried to remove what looked like an accidental unix focused setup so updated to 'os.sep'. But looks like the Plex team are the ones with unix on the brain :)

**Comment by ZeroQI** [comment]
I had the same reflex when i saw it, brilliant a bug gone, then checked the documentation and well...
Thnaks for all the other fixes, it removes quite few bugs and source is simpler in places
I unfortunately lack more and more time for coding
Am nearly done with Lambda, and import/export agent creating posters and NFO from plex meta and am finishing the XML adding function...

**Comment by EndOfLine369** [comment]
Looks like it totaled to 74 commits in the last month. 😄 
Glad to help to make the scanner batter and as bug free as I can make it.

**Comment by ZeroQI** [comment]
That's one raising agent :p
Will have to move logs to Plex logs folders at some point.

**Pull request merged**
