### PR TITLE
Multiple Updates

### PR DESCRIPTION
**Pull request by EndOfLine369**
- TVDB modes season & ep offset
- "anidb2" mode for automatic scudlee offset
- "rawgit.com" url update
- Static variable CAPS
- Update for log rotation & persistent file handle
- Log level additions

### CODE REVIEW

**Comment by EndOfLine369** [comment]
Related to https://github.com/ZeroQI/Absolute-Series-Scanner/issues/46

**Comment by EndOfLine369** [comment]
@ZeroQI please leave for me to merge. But do take a look. No reductions at this time :wink:

**Comment by EndOfLine369** [comment]
EX of logging post update.
```
2016-07-24 06:17:56,865 - ASS - "Fairy Tail -f -lj -s10 -e175 -a6662 [anidb-6662] -n10942" s0001e047 "[Kyuubi]_Fairy_Tail_47_[720p][2A98B359].mp4"
2016-07-24 06:17:56,869 - ASS - "Fairy Tail -f -lj -s10 -e175 -a6662 [anidb-6662] -n10942" s0001e048 "[Kyuubi]_Fairy_Tail_48_[720p][F73E6DF6].mp4"
2016-07-24 06:17:56,873 - ASS - "Fairy Tail -f -lj -s10 -e175 -a6662 [anidb-6662] -n10942" s0001e049 "[Kyuubi]_Fairy_Tail_49_[720p][380EE21D].mp4"
2016-07-24 06:17:56,877 - ASS - "Fairy Tail -f -lj -s10 -e175 -a6662 [anidb-6662] -n10942" s0001e050 "[Kyuubi]_Fairy_Tail_50_[720p][32F0AE36].mp4"
```

**Comment by ZeroQI** [comment]
"@ZeroQI please leave for me to merge. But do take a look. No reductions at this time :wink:"
Sir! Yes, Sir! :D

Could we not load the "+import tempfile" before line 394 so it's only loaded if user uses anidb2?
I like static variables in uppercase, makes it more readable, consistent, logical.
You don't like if statement and action on a single line it seems. I know it is better fr clarity, as too long lines messed up the error line reported in errors and made my life hell before when troubleshooting

Very nice commit. more readable. Thank you.

**Comment by EndOfLine369** [comment]
Re import, take a read [HERE](https://wiki.python.org/moin/PythonSpeed/PerformanceTips#Import_Statement_Overhead). We could move the import i guess but would probably need to add in the noted test to see if it is already imported as well otherwise we will possibly hit performance issues from the repeated imports. To my understanding (could be wrong), imports only increase a process' memory and not efficiency so I see no reason to not import at load.

**Comment by ZeroQI** [comment]
"This is only a significant saving in cases where the module wouldn't have been imported at all (from any module) -- if the module is already loaded (as will be the case for many standard modules, like string or re), avoiding an import doesn't save you anything."
hummm very interesting link.
Dang, let's leave as it is. well played :D

**Comment by EndOfLine369** [comment]
Add in log levels as well now.

**Comment by ZeroQI** [comment]
Nice

On a separate note, found this searching forum posts about the scanner
https://www.youtube.com/watch?v=XMCDZtAQEWY&app=desktop

Do you have any idea for improvement, because i can't think of any right now apart importing the scanner filelist as library. Hama could make the caching of data optional in app data folders but like the security of anything not available can be loaded with the last version...

**Comment by EndOfLine369** [comment]
Interesting video. With the main ticket closed will merge now

**Comment by EndOfLine369** [comment]
We could look at the media stubs. Once I understand what it is :wink:

**Comment by ZeroQI** [comment]
It is a placeholder file to represent a dvd or other disc you own and path to the drive. You are meant to insert the disk in an optical drive to play the movie or episode like you would any other file. For us that would allow to have a library of fake items the user have irl.
Considered doing a ps3/4 game agent to use plex nice display at some point or rom agent using mame db flat files...

**Comment by ZeroQI** [comment]
I did delete the former pull request and created a new one: https://github.com/ZeroQI/Hama.bundle/pull/71

It supports both series and movies using themoviedb. i called themoviedb movies TMDB and the series part TSDB (for TheSeriesDB) since themoviedb ids overlap otherwise so we can force themoviedb series id like "Naruto [tsdb-46260]" and have metadata from themoviedb (good if thetvdb is down)

The scanner seem already able for that...

**Pull request merged**
