### PR TITLE
Grouping folder & filelist updates

### PR DESCRIPTION
**Pull request by EndOfLine369**

### CODE REVIEW

**Comment by EndOfLine369** [comment]
@ZeroQI, looks like i messed up logging some as Plex files are added at the end outside the series folder scan. Please tweak/add the logging to meet your new requirements.

**Comment by ZeroQI** [comment]
the grouping prevent caching and skipping if nothing changed so longer runs...
might make it an agent option checked by the scanner to use root scan for grouping folders.
I did bring back legacy scanner for that reason, as it added all on root scan

**Comment by EndOfLine369** [comment]
Maybe I can put in an initial scan of all folders in a root and if any "[grouping]" are seen, we do the way it was just updated too. And if not seen, it uses Plex's call on what folders to scan?

**Comment by EndOfLine369** [comment]
That way its not an option they forget to enable for grouping folders.

**Comment by ZeroQI** [comment]
First, thanks again for your help!

The very reason i passed from the legacy scanner with all files scanned on root and the way that give grouping folders issues is that i had corruptions (which may have been more coding caused issues than the method) and i wanted to use proper Plex caching as if a folder content didn't change, it is skipped for the next scan.

I suggest we leave the folder scan unless a grouping folder we do these folders only in root.
I would not like to penalize normal users following Plex naming convention, but bot having to add grouping folders is a feature no other tool has so worth the counter-cost of no caching.

Series logs are purges on scan, which means a meta refresh is needed to have agent logs per serie if this is not a newly recreated library...

What do you think about the per-serie logging? Clever ? I thought it would be easier to tell people to refresh the serie then give me the serie log...

**Comment by EndOfLine369** [comment]
Your 'Corruptions' are probably as you didn't sort the files before adding into the mediaList. If files are added into mediaList where it goes SeriesX, SeriesY, SeriesX again. It will not get added into Plex correctly if not in series order. It must be all entries for SeriesX then the full next series on all entries from a single Plex triggered folder Scan call. 
You can actually see this in the live scanner on root folder files if their names don't put all of a single series together. That is because in the root folder, the series name is determined by the filename and not based on the containing folder so you will have multiple series defined from a single scan.

I'll update the scanner to look at all root sub-folders for "[grouping]" in their name. If found, full recursive scan from the root folder Plex scan. Else, let Plex determine the folders to scan.

**Comment by EndOfLine369** [comment]
I have done that now. https://github.com/ZeroQI/Absolute-Series-Scanner/commit/0d0324f0bfc06c78f7da14ed8ed80392e6a4bc50

**Pull request merged**
