### PR TITLE
Code reduction

### PR DESCRIPTION
**Pull request by ZeroQI**
Further code reduction [down to 407 lines]:
. removed seasonsfromfolder file
. removed zerofilesize file
. abs_manual_placement_worked replaced by else
. urrlib python 3 included

### CODE REVIEW

**Comment by EndOfLine369** [comment]
Still reviewing but put in my initial updates

**Comment by ZeroQI** [comment]
Thanks. It should be less messy than the agent.
I like themoviedb. If there is a tvdb issue it's a good backup. Will have to work on search to include results for it maybe. 

Would love a tvdb offline title and id file. Found one from last year but no possibility to generate one...

Let me know if you have any idea for feature request.
Doing a metadata table and we may be able to add season summary for exemple...

**Comment by EndOfLine369** [comment]
Not sure if you noticed but the search function in HAMA is currently stopping before any real searches outside of AniDB. https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py#L177

**Comment by ZeroQI** [comment]
Now i do. How could i miss that?
I have been wondering why i couldn't see tvdb guids in search... it helps with american animation which are not in anidb.

**Comment by EndOfLine369** [comment]
I think that is most of the reduction updates to get it working. Will do a full test when I have the time in the next couple of days and merge if it passes.

**Comment by EndOfLine369** [comment]
Had to work the weekend and today was a holiday. I'll try to get this ironed out this week.

**Comment by EndOfLine369** [comment]
All testing was successful

**Pull request merged**
